source "https://rubygems.org"

ruby "3.0.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.1.0"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
# gem "rack-cors"


gem 'daemons'
gem 'delayed_job_active_record'
gem 'rest-client'

gem 'chunky_png', '~> 1.3', '>= 1.3.5' # has an security issue check https://www.rubydoc.info/gems/chunky_png/1.3.5 in "Security warning"

gem "os", "~> 1.1"

# commands
gem "net-ping", "~> 2.0"
gem "dnsruby", "~> 1.72"

group :development, :test do
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ]
  gem "brakeman", require: false
  gem 'awesome_print', '~> 1.8', require: 'ap'
  gem "rspec-rails", "~> 7.1"
end

gem 'awesome_print', '~> 1.8', require: 'ap'

gem "rubyzip", "~> 2.4"
