source "https://rubygems.org"

ruby file: '.ruby-version'

gem "rails", "~> 7.2.2", ">= 7.2.2.1"


gem 'pg', '~> 1.5', '>= 1.5.9'

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors"

# Env
gem 'dotenv', '~> 3.1', '>= 3.1.7'

# Session and auth
gem 'devise', '~> 4.9', '>= 4.9.4'
gem "jwt", "~> 2.10"

gem 'rest-client'


group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
  gem "brakeman", require: false
  gem 'awesome_print', '~> 1.8', require: 'ap'
end






