default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DB_USER") { '' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { '' } %>
  database: <%= ENV.fetch("DB_NAME") { '' } %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { '' } %>

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") { '' } %>
