source "https://rubygems.org"

ruby file: '.ruby-version'

gem "rails", "~> 7.2.2", ">= 7.2.2.1"


gem 'pg', '~> 1.5', '>= 1.5.9'

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"
# Use Redis adapter to run Action Cable in production
# gem "redis", ">= 4.0.1"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem "tzinfo-data", platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors"

# Env
gem 'dotenv', '~> 3.1', '>= 3.1.7'

# Session and auth
gem 'devise', '~> 4.9', '>= 4.9.4'
gem "jwt", "~> 2.10"

gem 'net-ssh', '~> 7.3'
# Dependencies for net-ssh
gem 'ed25519', '~> 1.3'
gem 'bcrypt_pbkdf', '~> 1.1', '>= 1.1.1'

gem "bugsnag", "~> 6.27"
gem "rubyzip", "~> 2.4"
gem "nokogiri", "~> 1.18"

# Steg
gem 'chunky_png', '~> 1.3', '>= 1.3.5' # has an security issue check https://www.rubydoc.info/gems/chunky_png/1.3.5 in "Security warning"

# Active jobs
gem 'delayed_job_active_record'
gem "daemons", "~> 1.4"

# files
gem "aws-sdk-s3", "~> 1.180"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
  gem "brakeman", require: false
  gem 'awesome_print', '~> 1.8', require: 'ap'
end

gem "net-scp", "~> 4.1"

gem "rest-client", "~> 2.1"
